name: Update Data

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Force delete DATA.txt if it exists
        run: |
          rm -f json/DATA.txt

      - name: Verify DATA.txt is deleted
        run: |
          if [ -f "json/DATA.txt" ]; then
            echo "DATA.txt was not deleted"
            exit 1
          else
            echo "DATA.txt successfully deleted"
          fi

      - name: Fetch Data
        run: |
          curl -v -L -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36" https://www.dextools.io/shared/data/pair?address=0xa43fe16908251ee70ef74718545e4fe6c5ccec9f\&chain=ether --output json/DATA.txt
      - name: Print fetched JSON data
        run: |
          cat json/DATA.txt
      - name: Check file permissions and ownership
        run: |
          ls -l json/DATA.txt
          stat json/DATA.txt
      - name: Commit changes
        env:
          TOKEN: ${{ secrets.secrettoastycode }}
        run: |
          git status
          git log --oneline -n 5
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote set-url origin https://${TOKEN}@github.com/ExposedToast/ExposedToast.github.io.git
          git fetch origin main
          git reset --hard origin/main
          git add json/DATA.txt
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update JSON data" && git push)
      - name: Print contents of DATA.txt
        run: |
          cat json/DATA.txt
        shell: bash
