name: Update Data

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set execute permissions for delete_data.sh
        run: chmod +x delete_data.sh

      - name: Delete DATA.txt and verify deletion
        run: ./delete_data.sh

      - name: Commit file deletion
        env:
          TOKEN: ${{ secrets.secrettoastycode }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote set-url origin https://${TOKEN}@github.com/ExposedToast/ExposedToast.github.io.git
          git rm json/DATA.txt
          git commit -m "Remove old DATA.txt"
          git push

      - name: Fetch Data
        run: |
          curl -v -L -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36" https://www.dextools.io/shared/data/pair?address=0xa43fe16908251ee70ef74718545e4fe6c5ccec9f\&chain=ether --output json/DATA.txt

      - name: Commit new data
        env:
          TOKEN: ${{ secrets.secrettoastycode }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote set-url origin https://${TOKEN}@github.com/ExposedToast/ExposedToast.github.io.git
          git add json/DATA.txt
          git commit -m "Update JSON data"
          git push

      - name: Print contents of DATA.txt
        run: |
          cat json/DATA.txt
        shell: bash
