name: Update JSON data

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.secrettoastycode }}

      - name: Fetch JSON data
        run: curl https://www.dextools.io/shared/data/pair?address=0xa43fe16908251ee70ef74718545e4fe6c5ccec9f&chain=ether > json/data.json

      - name: Commit changes
        env:
          TOKEN: ${{ secrets.secrettoastycode }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote set-url origin https://${TOKEN}@github.com/ExposedToast/ExposedToast.github.io.git
          git add json/data.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update JSON data" && git push origin main --force)
